### PR TITLE
Ramp up to 50 and add more article URLs

### PR DESCRIPTION
**Pull request by adgad**
/cc @commuterjoy @matthew-andrews  (arbitrarily chose 50, might be a bit overzealous)

### CODE REVIEW

**Comment by commuterjoy** [comment]
three points for bravery.

It would be nice to have a (graphite) dashboard that showed the critical path - cdn / router / preflight / app

**Comment by adgad** [comment]
Something like this?

https://www.hostedgraphite.com/bbaf3ccf/graphite/render/?width=586&height=308&_salt=1438076397.447&target=fastly.f8585BOxnGQDMbnkJoM1e.requests&target=sumSeries(heroku.preflight-requests.web_1.express.http.req.count%2Cheroku.preflight-requests.web_2.express.http.req.count)&target=sumSeries(heroku.next-router.web_3.http.req.pipe%2Cheroku.next-router.web_4.http.req.pipe%2Cheroku.next-router.web_1.http.req.pipe%2Cheroku.next-router.web_2.http.req.pipe)&target=sumSeries(heroku.article.web_1.express.http.req.count%2Cheroku.article.web_2.express.http.req.count)&target=sumSeries(heroku.front-page.web_2.express.http.req.count%2Cheroku.front-page.web_1.express.http.req.count)&target=sumSeries(heroku.ilyushin.web_1.express.http.req.count%2Cheroku.ilyushin.web_2.express.http.req.count%2Cheroku.ilyushin.web_3.express.http.req.count%2Cheroku.ilyushin.web_4.express.http.req.count)&target=sumSeries(heroku.stream-page.web_1.express.http.req.count%2Cheroku.stream-page.web_2.express.http.req.count)

**Comment by matthew-andrews** [comment]
what could possibly go wrong

**Comment by commuterjoy** [comment]
@adgad perfect. and one for errors? 

also you can replace the web_1, web_2 etc. with `*`

**Comment by adgad** [comment]
https://github.com/Financial-Times/next-graphite-dashboard/pull/31

*hits merge and looks away*

**Pull request merged**
